#67 #66
TIS2022-FMFI/spektra pull request #69
Opened 2022-12-17 22:30 UTC by lk0103

snake case, dokumentacia, refaktor a doladenie malych chybyciek

2022-12-17 23:58 UTC, Bonnie404 commented on models/data_processing/measurement_settings.py
> +    mandatory = [NAME_SAMPLE_KEY, NOTE_TO_TECH_KEY, THICKNESS_KEY,
Tento zoznam by mal byt oddeleny v constants

2022-12-18 01:42 UTC, Bonnie404 requested changes

2022-12-18 01:42 UTC, Bonnie404 commented on models/data_processing/measurement_settings.py
> +        """
Ak tomu spravne rozumiem, tak tu sme dospeli k stavu, ze mame objekt settings, ktory je vlastne json a potom nejaky measurements file, ktory obsahuje tieto settings ako legendu, len v nejakom divnom formate. Ak je to tak, tak to naozaj nie je moc dobre.

Navrhujem to zjednotit aspon tak, ze ta legenda measurement.txt bude json -> tz.bude vyzerat asi takto: {..settings.json}\n ..data.. . Potom staci pri nacitavani:

settings_string = get_hlavicka(filename) # vrati '{"bla": "bla", "ref": 30, "d": "s f"}'
legenda = json.loads(settings_string)
if legenda ma vsetky kluce mandatory:
	self.legenda <- legenda
else
	throw "cele zle"

potom aj tie vsetky ostatne metody by bud nebolo treba alebo by sa to minimalne sprehladnilo

2022-12-18 01:42 UTC, Bonnie404 commented on models/data_processing/measurement_settings.py
> +            if NAME_SAMPLE_KEY in self.legend.keys():
if NAME_SAMPLE_KEY in self.legend..

2022-12-18 01:42 UTC, Bonnie404 commented on models/data_processing/data_processing.py
> +class data_processing(QObject):
triedy sa oznacuju camel casom, aby to nebolo moc jednoduche :D tz, DataProcessing

2022-12-18 01:42 UTC, Bonnie404 commented on models/data_processing/data_processing.py
> +    def get_default_path(self):
toto by si tu ty nemala urcite zistovat takymto sposobom.. to kde sa ma ukladat to meranie by ti malo prist ako parameter.

Navrhujem si vytvorit nasledovny slovnik:

self.dict[cesta_k_suboru] = file_handle

def init_measurement(file_path):
	if not os.path.exists(file_path):
		return False
	self.dict[file_path] = open(file_path)
	self._write_legend(self.dict[file_path])
	return True

def add_measurement(file_path, a, b):
	if not os.path.exists(file_path) or if file_path not in self.dict::
		throw "ceel zle"
	
	self.dict[file_path].write(x,y,z)

def close_measurement(file_path):
	zavrie subor

def close_all_measurements():
	zavrie vsetky otvorene subory


skus upravit tuto triedu, aby obsahovala toto a potom aj upravit zvysok aby daval zmysel vzhladom na toto a myslim ze to bude o dost lepsie vo vysledku

2022-12-18 01:42 UTC, Bonnie404 commented on models/data_processing/grid.py
> +class grid:
triedy sa pisu camel case tz Grid

2022-12-25 11:37 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +        return SAMPLE + \
nemozu byt vsetky NAME_SAMPLE_KEY + self.legend[NAME_SAMPLE_KEY, kedze to nie je vzdy label a hodnota 1 k 1. Niekedy label nie je, niekedy je a niekedy k jednemu labelu su dve rozne hodnoty a tak som nechcela mat polku klucov  po slovensky a polu po  anglicky. Alebo celkovo ziadne kluce som nechcela mat po slovensky

2022-12-26 09:43 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +        """
to je blbost, lebo cely dovod preco musim komplikovane citat z toho starsieho suboru legendu je to, ze zadavatel chce mat pekne naformatovany udaj o merani. Ja to nemozem menit. A urcite nebude chciet mat legendu v json formate.

2022-12-26 10:14 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +    mandatory = [NAME_SAMPLE_KEY, NOTE_TO_TECH_KEY, THICKNESS_KEY,
vyriesene

2022-12-26 10:15 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +    def set_unit_type_position(self, unit_type_position):
vyriesene

2022-12-26 10:15 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +            if legend_type not in self.legend.keys():
vyriesene

2022-12-26 10:15 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +        all_setting_keys = self.mandatory  + self.non_mandatory
vyriesene

2022-12-26 10:15 UTC, lk0103 commented on models/data_processing/measurement_settings.py
> +            if NAME_SAMPLE_KEY in self.legend.keys():
vyriesene

2022-12-26 10:15 UTC, lk0103 commented on models/data_processing/grid.py
> +class grid:
vyriesene

2022-12-26 10:16 UTC, lk0103 commented on models/data_processing/data_processing.py
> +class data_processing(QObject):
vyriesene

2023-01-03 20:43 UTC, Bonnie404 approved these changes

2023-01-03 20:43 UTC, merged